# Persistant storage for the database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-datastore
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce