apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: laravel-test
  name: laravel-test
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: laravel-test
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sail: "true"
        io.kompose.service: laravel-test
    spec:
      containers:
        - env:
            - name: LARAVEL_SAIL
              value: "1"
            - name: WWWUSER
            - name: XDEBUG_CONFIG
              value: client_host=host.docker.internal
            - name: XDEBUG_MODE
              value: "off"
          image: sail-8.1/app
          name: laravel.test
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-test-claim0
      restartPolicy: Always
      volumes:
        - name: laravel-test-claim0
          persistentVolumeClaim:
            claimName: laravel-test-claim0
status: {}
