apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: laravel-test
  name: laravel-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: laravel-test
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/sail: "true"
        io.kompose.service: {{ .Release.Name }}-laravel-api
    spec:
      containers:
        - env:
            - name: LARAVEL_SAIL
              value: "1"
            - name: WWWUSER
            - name: XDEBUG_CONFIG
              value: client_host=host.docker.internal
            - name: XDEBUG_MODE
              value: "off"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: laravel-api
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
